frameTiledef = {
    "imageFile": "phylyp/frame.png",
    "colorKey": (0, 0, 0),
    "tileSize": (5, 5),
    "tiles": {
        "topLeft": (0, 0),
        "top": (1, 0),
        "topRight": (2, 0),
        "left": (0, 1),
        "center": (1, 1),
        "right": (2, 1),
        "bottomLeft": (0, 2),
        "bottom": (1, 2),
        "bottomRight": (2, 2),
        "elder": (3, 0, 3, 3),
        "melee_attack": (6, 0),
        "melee_defense": (7, 0),
        "range_attack": (8, 0),
        "range_defense": (9, 0),
        "mount_attack": (6, 1),
        "mount_defense": (7, 1),
        "siege_attack": (8, 1),
        "siege_defense": (9, 1),
        "life": (6, 2),
        "move": (7, 2),
        "attack": (8, 2),
        "flag": [(0, 3), (1, 3), (2, 3), (3, 3), (4, 3)],
        "food": (0, 4),
        "gold": (1, 4),
        "wood": (2, 4),
        "stone": (3, 4),
        "citizen": (6, 3),
        "worker": (6, 4),
        "merchant": (7, 4),
        "growth": (7, 3),
        "granary": (8, 3),
        "tool": (9, 3),
        "coin": (10, 3),
        "hourglass": [(0, 5, 2, 2), (2, 5, 2, 2), (4, 5, 2, 2), (6, 5, 2, 2), (8, 5, 2, 2)],
        "cursor": [(10, 0, 2, 2), (12, 0, 2, 2), (14, 0, 2, 2), (16, 0, 2, 2), (18, 0, 2, 2)],
        "leftclick": (10, 2),
        "rightclick": (11, 2),
    },
}
